# Generated by Django 4.1.4 on 2022-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capital", models.CharField(max_length=100)),
                ("area", models.IntegerField(help_text="(in square kilometers)")),
            ],
        ),
    ]
